chore: update cliffy to 0.10.0
nestdotland/eggs pull request #14
Opened 2020-07-13 12:32 UTC by oganexon

2020-07-13 22:07 UTC, t8 commented
This portion of `deps.ts` is still on Cliffy v0.9.0:

```ts
export {
  Input,
  Confirm,
  List,
} from "https://deno.land/x/cliffy@v0.9.0/prompt.ts";
```

2020-07-13 22:09 UTC, t8 requested changes
Everything looks good except for that other cliffy import and the fact that you aren't importing Cliffy `0.10.0` from nest.land. Is it meant to be kept at 0.9.0?

2020-07-13 22:09 UTC, t8 commented on deps.ts
> +} from "https://deno.land/x/cliffy@v0.10.0/command.ts";
```suggestion
} from "https://x.nest.land/cliffy@0.10.0/command.ts";
```
😉

2020-07-13 22:11 UTC, oganexon commented on deps.ts
> +} from "https://deno.land/x/cliffy@v0.10.0/command.ts";
Not at all, I'll change that right away

2020-07-14 16:02 UTC, qu4k commented
On hold until https://github.com/c4spar/deno-cliffy/pull/45 gets merged.

2020-07-14 21:16 UTC, merged